default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: "<%= ENV['local_database_user'] %>"
  password: "<%= ENV['local_database_pass'] %>"

development:
  <<: *default
  database: delivery_ruby_development

test:
  <<: *default
  database: delivery_ruby_test

production:
  <<: *default
  database: delivery_ruby_production
